### ISSUE TITLE
[Q] Is it possible to apply attribute to all assembly ?

### ISSUE THREAD

**Issue by goblinmaks** [bt-skyrise/NUnitRetrying#1]
Is it possible to apply this attribute in one place to apply for each test in assembly ?
Is it possible to implement it ?
Thanks,

**Comment by redss** [comment]
Hello goblinmaks,

Unfortunately, I'm almost sure `RetryingAttribute` can't be used on assembly level, even if you change `AttributeUsage` to enable it. I guess this is how attributes implementing `IWrapSetUpTearDown` work.

Is it possible to implement? Sadly, I've no idea. I haven't mentioned it in readme.md until today, but this repository is just a POC used in a blog post: [Extending NUnit 3 with command wrappers](https://www.skyrise.tech/blog/tech/extending-nunit-3-with-command-wrappers/). After publishing a blog post I haven't really have a need to maintain this repo and to dig deeper into NUnit attributes. Also, this was implemented two years ago - NUnit's extension model might have changed since then.

I think your best bet is to ask folks at NUnit if creating such attribute is possible. You can also read my [blog post](https://www.skyrise.tech/blog/tech/extending-nunit-3-with-command-wrappers/) for some clues on implementing such attribute (and on why I've used `IWrapSetUpTearDown` instead of more mainstream [Action Attributes](https://github.com/nunit/docs/wiki/Action-Attributes) option).

Good luck and best regards,
RT
